/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class InicioSesion extends javax.swing.JFrame {

        String username = "aa";
    String Pass = "aa";
    
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtContraseña = new javax.swing.JTextField();
        lblInicioSesion = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnRegistrarse = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        btnContinuar1 = new javax.swing.JButton();
        lblContraseña = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnContinuar2 = new javax.swing.JButton();

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ADMIN\\Downloads\\aa.png")); // NOI18N
        jLabel4.setText("Usuario:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(240, 270));
        getContentPane().setLayout(null);

        txtUsuario.setBackground(new java.awt.Color(255, 204, 102));
        txtUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        getContentPane().add(txtUsuario);
        txtUsuario.setBounds(100, 40, 90, 16);

        txtContraseña.setBackground(new java.awt.Color(255, 204, 102));
        txtContraseña.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraseña);
        txtContraseña.setBounds(100, 70, 90, 16);

        lblInicioSesion.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblInicioSesion.setText("Inicio de Sesión");
        getContentPane().add(lblInicioSesion);
        lblInicioSesion.setBounds(0, 0, 120, 16);

        btnSalir.setBackground(new java.awt.Color(255, 204, 102));
        btnSalir.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setAutoscrolls(true);
        btnSalir.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102), 15));
        btnSalir.setBorderPainted(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(70, 190, 70, 20);

        btnRegistrarse.setBackground(new java.awt.Color(255, 204, 102));
        btnRegistrarse.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setAutoscrolls(true);
        btnRegistrarse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102), 15));
        btnRegistrarse.setBorderPainted(false);
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarse);
        btnRegistrarse.setBounds(50, 160, 110, 23);

        lblUsuario.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblUsuario.setText("Usuario:");
        getContentPane().add(lblUsuario);
        lblUsuario.setBounds(30, 40, 60, 16);

        btnContinuar1.setBackground(new java.awt.Color(255, 204, 102));
        btnContinuar1.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnContinuar1.setText("Continuar");
        btnContinuar1.setAutoscrolls(true);
        btnContinuar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102), 15));
        btnContinuar1.setBorderPainted(false);
        btnContinuar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnContinuar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar1);
        btnContinuar1.setBounds(60, 130, 90, 20);

        lblContraseña.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblContraseña.setText("Contraseña:");
        getContentPane().add(lblContraseña);
        lblContraseña.setBounds(10, 70, 77, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Inicio de Sesión (4).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 220, 220);

        btnContinuar2.setBackground(new java.awt.Color(255, 204, 102));
        btnContinuar2.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnContinuar2.setText("Continuar");
        btnContinuar2.setAutoscrolls(true);
        btnContinuar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102), 15));
        btnContinuar2.setBorderPainted(false);
        btnContinuar2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnContinuar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuar2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar2);
        btnContinuar2.setBounds(60, 130, 90, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
      this.dispose();
          

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        RegistroUsuario r = new RegistroUsuario();
        this.hide();
        r.show();
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnContinuar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuar1ActionPerformed
            if ( this.txtUsuario.getText().equals(username)) {
            if (this.txtContraseña.getText().equals(Pass)) {
               Menu m = new Menu();
               m.show();
            }else {
                JOptionPane.showMessageDialog(rootPane, "Contraseña incorrecta, verifique");
            }

        }else{
            JOptionPane.showMessageDialog(rootPane, "Usuario incorrecta, verifique");
        }
    }//GEN-LAST:event_btnContinuar1ActionPerformed

    private void btnContinuar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnContinuar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar1;
    private javax.swing.JButton btnContinuar2;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblInicioSesion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
