/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author ADMIN
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenu = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnRegistroAviones = new javax.swing.JButton();
        btnAsignarVuelo = new javax.swing.JButton();
        btnRegistroViajes = new javax.swing.JButton();
        btnRegistroPasajeros = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(240, 280));
        getContentPane().setLayout(null);

        lblMenu.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblMenu.setText("Menú");
        getContentPane().add(lblMenu);
        lblMenu.setBounds(0, 0, 40, 16);

        btnSalir.setBackground(new java.awt.Color(231, 249, 247));
        btnSalir.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnSalir.setContentAreaFilled(false);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(70, 200, 80, 19);

        btnRegistroAviones.setBackground(new java.awt.Color(231, 249, 247));
        btnRegistroAviones.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnRegistroAviones.setText("<html> <center> Registro de Aviones <br/> </center> </html>");
        btnRegistroAviones.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnRegistroAviones.setContentAreaFilled(false);
        btnRegistroAviones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroAvionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroAviones);
        btnRegistroAviones.setBounds(50, 70, 120, 30);

        btnAsignarVuelo.setBackground(new java.awt.Color(231, 249, 247));
        btnAsignarVuelo.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnAsignarVuelo.setText("<html> <center> Asignar un <br/> Vuelo  </center> </html>");
        btnAsignarVuelo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnAsignarVuelo.setContentAreaFilled(false);
        btnAsignarVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarVueloActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsignarVuelo);
        btnAsignarVuelo.setBounds(50, 150, 120, 30);

        btnRegistroViajes.setBackground(new java.awt.Color(231, 249, 247));
        btnRegistroViajes.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnRegistroViajes.setText("<html><center> Registro <br/> de Viajes </center></html>");
        btnRegistroViajes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnRegistroViajes.setContentAreaFilled(false);
        btnRegistroViajes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRegistroViajes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistroViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroViajesActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroViajes);
        btnRegistroViajes.setBounds(50, 30, 120, 30);

        btnRegistroPasajeros.setBackground(new java.awt.Color(231, 249, 247));
        btnRegistroPasajeros.setFont(new java.awt.Font("Monospaced", 1, 12)); // NOI18N
        btnRegistroPasajeros.setText("<html> <center> Registro de Pasajeros <br/> </center></html>");
        btnRegistroPasajeros.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnRegistroPasajeros.setContentAreaFilled(false);
        btnRegistroPasajeros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroPasajerosActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistroPasajeros);
        btnRegistroPasajeros.setBounds(50, 110, 120, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/image.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, -10, 230, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroViajesActionPerformed
        RegistroViajes r = new RegistroViajes();
        this.hide();
        r.show();
    }//GEN-LAST:event_btnRegistroViajesActionPerformed

    private void btnRegistroAvionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroAvionesActionPerformed
       RegistroAviones r = new RegistroAviones();
       this.hide();
       r.show();
    }//GEN-LAST:event_btnRegistroAvionesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistroPasajerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroPasajerosActionPerformed
       RegistroPasajeros r = new RegistroPasajeros();
       this.hide();
       r.show();
    }//GEN-LAST:event_btnRegistroPasajerosActionPerformed

    private void btnAsignarVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarVueloActionPerformed
       RegistroViajeEspecifico r = new RegistroViajeEspecifico();
       this.hide();
       r.show();
    }//GEN-LAST:event_btnAsignarVueloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignarVuelo;
    private javax.swing.JButton btnRegistroAviones;
    private javax.swing.JButton btnRegistroPasajeros;
    private javax.swing.JButton btnRegistroViajes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblMenu;
    // End of variables declaration//GEN-END:variables
}
