/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author ADMIN
 */
public class RegistroViajes extends javax.swing.JFrame {

    /**
     * Creates new form RegistroViajes
     */
    public RegistroViajes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblRegistroViajes = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lblFechaVuelo = new javax.swing.JLabel();
        lblCostoBoleto = new javax.swing.JLabel();
        lblHoraSalida = new javax.swing.JLabel();
        txtHoraSalida = new javax.swing.JTextField();
        txtCostoBoleto = new javax.swing.JTextField();
        txtCiudad = new javax.swing.JTextField();
        txtFechaVuelo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        cboPais = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblViajes = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 350));
        getContentPane().setLayout(null);

        lblRegistroViajes.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblRegistroViajes.setText("Registro de Viajes:");
        getContentPane().add(lblRegistroViajes);
        lblRegistroViajes.setBounds(0, 0, 164, 16);

        lblPais.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblPais.setText("País:");
        getContentPane().add(lblPais);
        lblPais.setBounds(70, 40, 80, 16);

        lblCiudad.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblCiudad.setText("Ciudad:");
        getContentPane().add(lblCiudad);
        lblCiudad.setBounds(50, 80, 60, 16);

        lblFechaVuelo.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblFechaVuelo.setText("Fecha Vuelo:");
        getContentPane().add(lblFechaVuelo);
        lblFechaVuelo.setBounds(20, 160, 120, 20);

        lblCostoBoleto.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblCostoBoleto.setText("Costo Boleto:");
        getContentPane().add(lblCostoBoleto);
        lblCostoBoleto.setBounds(10, 200, 120, 16);

        lblHoraSalida.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblHoraSalida.setText("Hora Salida:");
        getContentPane().add(lblHoraSalida);
        lblHoraSalida.setBounds(20, 120, 120, 16);

        txtHoraSalida.setEditable(false);
        txtHoraSalida.setBackground(new java.awt.Color(255, 245, 222));
        txtHoraSalida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtHoraSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHoraSalidaActionPerformed(evt);
            }
        });
        getContentPane().add(txtHoraSalida);
        txtHoraSalida.setBounds(120, 120, 90, 16);

        txtCostoBoleto.setEditable(false);
        txtCostoBoleto.setBackground(new java.awt.Color(255, 245, 222));
        txtCostoBoleto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCostoBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoBoletoActionPerformed(evt);
            }
        });
        getContentPane().add(txtCostoBoleto);
        txtCostoBoleto.setBounds(120, 200, 90, 16);

        txtCiudad.setEditable(false);
        txtCiudad.setBackground(new java.awt.Color(255, 245, 222));
        txtCiudad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCiudadActionPerformed(evt);
            }
        });
        getContentPane().add(txtCiudad);
        txtCiudad.setBounds(120, 80, 90, 16);

        txtFechaVuelo.setEditable(false);
        txtFechaVuelo.setBackground(new java.awt.Color(255, 245, 222));
        txtFechaVuelo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtFechaVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaVueloActionPerformed(evt);
            }
        });
        getContentPane().add(txtFechaVuelo);
        txtFechaVuelo.setBounds(120, 160, 90, 16);

        btnEliminar.setBackground(new java.awt.Color(255, 245, 222));
        btnEliminar.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEliminar.setContentAreaFilled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(120, 240, 60, 17);

        btnVolverMenu.setBackground(new java.awt.Color(255, 245, 222));
        btnVolverMenu.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnVolverMenu.setText("Volver al Menú");
        btnVolverMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnVolverMenu.setContentAreaFilled(false);
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverMenu);
        btnVolverMenu.setBounds(60, 260, 110, 20);

        btnGuardar.setBackground(new java.awt.Color(255, 245, 222));
        btnGuardar.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(50, 240, 60, 17);

        cboPais.setBackground(new java.awt.Color(255, 245, 222));
        cboPais.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(cboPais);
        cboPais.setBounds(120, 40, 90, 20);

        jScrollPane4.setToolTipText("");
        jScrollPane4.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tblViajes.setBackground(new java.awt.Color(255, 245, 222));
        tblViajes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "País", "Ciudad"
            }
        ));
        jScrollPane4.setViewportView(tblViajes);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(230, 40, 210, 240);

        jPanel1.setBackground(new java.awt.Color(255, 245, 222));
        jPanel1.setLayout(null);
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -20, 500, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtHoraSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHoraSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHoraSalidaActionPerformed

    private void txtCostoBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoBoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoBoletoActionPerformed

    private void txtCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCiudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCiudadActionPerformed

    private void txtFechaVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaVueloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaVueloActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
            Menu m = new Menu();
       this.hide();
       m.show();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroViajes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroViajes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JComboBox<String> cboPais;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCostoBoleto;
    private javax.swing.JLabel lblFechaVuelo;
    private javax.swing.JLabel lblHoraSalida;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblRegistroViajes;
    private javax.swing.JTable tblViajes;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCostoBoleto;
    private javax.swing.JTextField txtFechaVuelo;
    private javax.swing.JTextField txtHoraSalida;
    // End of variables declaration//GEN-END:variables
}
