/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author ADMIN
 */
public class RegistroPasajeros extends javax.swing.JFrame {

    /**
     * Creates new form RegistroPasajeros
     */
    public RegistroPasajeros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistroPasajeros = new javax.swing.JLabel();
        lblNombrePasajero = new javax.swing.JLabel();
        lblNumeroAsiento = new javax.swing.JLabel();
        lblPasaporte = new javax.swing.JLabel();
        lblClase = new javax.swing.JLabel();
        lblMarcaAvion = new javax.swing.JLabel();
        txtMarcaAvion = new javax.swing.JTextField();
        txtClase = new javax.swing.JTextField();
        txtNombrePasajero = new javax.swing.JTextField();
        txtNumeroAsiento = new javax.swing.JTextField();
        txtPasaporte = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPasajeros = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(null);

        lblRegistroPasajeros.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblRegistroPasajeros.setText("Registro de Pasajeros:");
        getContentPane().add(lblRegistroPasajeros);
        lblRegistroPasajeros.setBounds(0, 0, 164, 16);

        lblNombrePasajero.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblNombrePasajero.setText("Nombre del Pasajero:");
        getContentPane().add(lblNombrePasajero);
        lblNombrePasajero.setBounds(10, 60, 140, 16);

        lblNumeroAsiento.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblNumeroAsiento.setText("Número de asiento:");
        getContentPane().add(lblNumeroAsiento);
        lblNumeroAsiento.setBounds(20, 100, 130, 16);

        lblPasaporte.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblPasaporte.setText("Pasaporte:");
        getContentPane().add(lblPasaporte);
        lblPasaporte.setBounds(70, 180, 120, 20);

        lblClase.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblClase.setText("Clase:");
        getContentPane().add(lblClase);
        lblClase.setBounds(100, 220, 120, 10);

        lblMarcaAvion.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblMarcaAvion.setText("Marca de Avión:");
        getContentPane().add(lblMarcaAvion);
        lblMarcaAvion.setBounds(40, 140, 120, 16);

        txtMarcaAvion.setEditable(false);
        txtMarcaAvion.setBackground(new java.awt.Color(177, 193, 208));
        txtMarcaAvion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMarcaAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaAvionActionPerformed(evt);
            }
        });
        getContentPane().add(txtMarcaAvion);
        txtMarcaAvion.setBounds(160, 140, 90, 16);

        txtClase.setEditable(false);
        txtClase.setBackground(new java.awt.Color(177, 193, 208));
        txtClase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaseActionPerformed(evt);
            }
        });
        getContentPane().add(txtClase);
        txtClase.setBounds(160, 220, 90, 16);

        txtNombrePasajero.setEditable(false);
        txtNombrePasajero.setBackground(new java.awt.Color(177, 193, 208));
        txtNombrePasajero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNombrePasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombrePasajeroActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombrePasajero);
        txtNombrePasajero.setBounds(160, 60, 90, 16);

        txtNumeroAsiento.setEditable(false);
        txtNumeroAsiento.setBackground(new java.awt.Color(177, 193, 208));
        txtNumeroAsiento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtNumeroAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroAsientoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumeroAsiento);
        txtNumeroAsiento.setBounds(160, 100, 90, 16);

        txtPasaporte.setEditable(false);
        txtPasaporte.setBackground(new java.awt.Color(177, 193, 208));
        txtPasaporte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPasaporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasaporteActionPerformed(evt);
            }
        });
        getContentPane().add(txtPasaporte);
        txtPasaporte.setBounds(160, 180, 90, 16);

        btnEliminar.setBackground(new java.awt.Color(177, 193, 208));
        btnEliminar.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(160, 270, 60, 17);

        btnVolverMenu.setBackground(new java.awt.Color(177, 193, 208));
        btnVolverMenu.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnVolverMenu.setText("Volver al Menú");
        btnVolverMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolverMenu);
        btnVolverMenu.setBounds(90, 300, 110, 20);

        btnGuardar.setBackground(new java.awt.Color(177, 193, 208));
        btnGuardar.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(70, 270, 60, 17);

        tblPasajeros.setBackground(new java.awt.Color(177, 193, 208));
        tblPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre de Pasajero", "Número Asiento"
            }
        ));
        jScrollPane1.setViewportView(tblPasajeros);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(280, 60, 270, 190);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/avuib.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 570, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMarcaAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaAvionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaAvionActionPerformed

    private void txtClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaseActionPerformed

    private void txtNombrePasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombrePasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombrePasajeroActionPerformed

    private void txtNumeroAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroAsientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroAsientoActionPerformed

    private void txtPasaporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasaporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasaporteActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
          Menu m = new Menu();
          this.hide();
          m.show();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroPasajeros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroPasajeros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClase;
    private javax.swing.JLabel lblMarcaAvion;
    private javax.swing.JLabel lblNombrePasajero;
    private javax.swing.JLabel lblNumeroAsiento;
    private javax.swing.JLabel lblPasaporte;
    private javax.swing.JLabel lblRegistroPasajeros;
    private javax.swing.JTable tblPasajeros;
    private javax.swing.JTextField txtClase;
    private javax.swing.JTextField txtMarcaAvion;
    private javax.swing.JTextField txtNombrePasajero;
    private javax.swing.JTextField txtNumeroAsiento;
    private javax.swing.JTextField txtPasaporte;
    // End of variables declaration//GEN-END:variables
}
