/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author ADMIN
 */
public class RegistroAviones extends javax.swing.JFrame {

    /**
     * Creates new form RegistroAviones
     */
    public RegistroAviones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        lblRegistroAviones = new javax.swing.JLabel();
        lblCargaMaxima = new javax.swing.JLabel();
        lblTipoAvion = new javax.swing.JLabel();
        lblIdentificador = new javax.swing.JLabel();
        lblPasajeroMax = new javax.swing.JLabel();
        lblPesoMaximo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnVolverMenu = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblAviones = new javax.swing.JTable();
        txtCargaMaxima = new javax.swing.JTextField();
        txtPesoMaximo = new javax.swing.JTextField();
        txtPasajeroMax = new javax.swing.JTextField();
        txtIdentificador = new javax.swing.JTextField();
        txtTipoAvion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 153, 102));
        setMinimumSize(new java.awt.Dimension(503, 400));
        getContentPane().setLayout(null);

        lblRegistroAviones.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblRegistroAviones.setText("Registro de Aviones");
        getContentPane().add(lblRegistroAviones);
        lblRegistroAviones.setBounds(0, 0, 150, 16);

        lblCargaMaxima.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblCargaMaxima.setText("Carga Maxima:");
        getContentPane().add(lblCargaMaxima);
        lblCargaMaxima.setBounds(20, 210, 100, 16);

        lblTipoAvion.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblTipoAvion.setText("Tipo de Avion:");
        getContentPane().add(lblTipoAvion);
        lblTipoAvion.setBounds(20, 50, 120, 16);

        lblIdentificador.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblIdentificador.setText("Identificador:");
        getContentPane().add(lblIdentificador);
        lblIdentificador.setBounds(20, 90, 110, 16);

        lblPasajeroMax.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblPasajeroMax.setText("Pasajero Max:");
        getContentPane().add(lblPasajeroMax);
        lblPasajeroMax.setBounds(20, 130, 110, 16);

        lblPesoMaximo.setFont(new java.awt.Font("Monospaced", 1, 11)); // NOI18N
        lblPesoMaximo.setText("Peso Maximo:");
        getContentPane().add(lblPesoMaximo);
        lblPesoMaximo.setBounds(20, 170, 100, 16);

        jPanel1.setBackground(new java.awt.Color(253, 228, 215));
        jPanel1.setLayout(null);

        btnEliminar.setBackground(new java.awt.Color(255, 226, 211));
        btnEliminar.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnEliminar.setContentAreaFilled(false);
        jPanel1.add(btnEliminar);
        btnEliminar.setBounds(110, 270, 60, 17);

        btnGuardar.setBackground(new java.awt.Color(255, 244, 237));
        btnGuardar.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(40, 270, 60, 17);

        btnVolverMenu.setBackground(new java.awt.Color(255, 244, 237));
        btnVolverMenu.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        btnVolverMenu.setText("Volver al Menú");
        btnVolverMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        btnVolverMenu.setContentAreaFilled(false);
        btnVolverMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolverMenu);
        btnVolverMenu.setBounds(50, 300, 110, 17);

        jScrollPane3.setToolTipText("");
        jScrollPane3.setViewportBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        tblAviones.setBackground(new java.awt.Color(255, 244, 237));
        tblAviones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tipo de Avion", "Identifiicador"
            }
        ));
        jScrollPane3.setViewportView(tblAviones);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(230, 50, 250, 190);

        txtCargaMaxima.setEditable(false);
        txtCargaMaxima.setBackground(new java.awt.Color(255, 244, 237));
        txtCargaMaxima.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCargaMaxima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargaMaximaActionPerformed(evt);
            }
        });
        jPanel1.add(txtCargaMaxima);
        txtCargaMaxima.setBounds(120, 210, 90, 16);

        txtPesoMaximo.setEditable(false);
        txtPesoMaximo.setBackground(new java.awt.Color(255, 244, 237));
        txtPesoMaximo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPesoMaximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoMaximoActionPerformed(evt);
            }
        });
        jPanel1.add(txtPesoMaximo);
        txtPesoMaximo.setBounds(120, 170, 90, 16);

        txtPasajeroMax.setBackground(new java.awt.Color(255, 244, 237));
        txtPasajeroMax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtPasajeroMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasajeroMaxActionPerformed(evt);
            }
        });
        jPanel1.add(txtPasajeroMax);
        txtPasajeroMax.setBounds(120, 130, 90, 16);

        txtIdentificador.setEditable(false);
        txtIdentificador.setBackground(new java.awt.Color(255, 244, 237));
        txtIdentificador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificadorActionPerformed(evt);
            }
        });
        jPanel1.add(txtIdentificador);
        txtIdentificador.setBounds(120, 90, 90, 16);

        txtTipoAvion.setEditable(false);
        txtTipoAvion.setBackground(new java.awt.Color(255, 244, 237));
        txtTipoAvion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtTipoAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoAvionActionPerformed(evt);
            }
        });
        jPanel1.add(txtTipoAvion);
        txtTipoAvion.setBounds(120, 50, 90, 16);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/grezia.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, 20, 300, 270);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 500, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCargaMaximaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargaMaximaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargaMaximaActionPerformed

    private void txtTipoAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoAvionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoAvionActionPerformed

    private void txtIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificadorActionPerformed

    private void txtPasajeroMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasajeroMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasajeroMaxActionPerformed

    private void txtPesoMaximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoMaximoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoMaximoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnVolverMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverMenuActionPerformed
           Menu m = new Menu();
       this.hide();
       m.show();
    }//GEN-LAST:event_btnVolverMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroAviones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroAviones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolverMenu;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCargaMaxima;
    private javax.swing.JLabel lblIdentificador;
    private javax.swing.JLabel lblPasajeroMax;
    private javax.swing.JLabel lblPesoMaximo;
    private javax.swing.JLabel lblRegistroAviones;
    private javax.swing.JLabel lblTipoAvion;
    private javax.swing.JTable tblAviones;
    private javax.swing.JTextField txtCargaMaxima;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtPasajeroMax;
    private javax.swing.JTextField txtPesoMaximo;
    private javax.swing.JTextField txtTipoAvion;
    // End of variables declaration//GEN-END:variables
}
